name: Dispatch Parent Repo Update

on:
  push:
    branches:
      - master # Trigger when commits are pushed to the master branch of the blog content repo

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch parent repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MBRZOZOWSKI_WEBSITE_REPO_PAT }} # PAT for the parent repository
          repository: marcin-brzozowski/marcinbrzozowski-website # The parent repository
          event-type: blog_submodule_update # Custom event type for the parent workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
